name: Deploy

on:
  push:
    branch-ignore:
      - main
      - master

jobs:
  run-junit-test:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Step Java
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Step Maven
        uses: stCarolas/setup-maven@4.4
        with:
          maven-version: 3.8.2

      - name: JUnit Test
        run: mvn clean package

      - name: Rename the artifact
        run: cp target/todo-0.0.1-SNAPSHOT-jar-with-dependencies.jar todo-{{ github-sha }}.jar

      - name: Save the artifact
        run: actions/upload-artifact@master
        with:
          name: todo
          path: todo-{{ github.sha }}.jar

  fake-deploy:
    run-on: self-hosted
    need: run-unit-tests
    steps:
      - name: Get the artifact
        uses: action/download-artifact@main
        with:
          name: todo

      - name: Fake deploy
        run: ls todo*.jar